# Generated by Django 2.0.5 on 2018-05-08 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_str', models.TextField(verbose_name='body')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                ('created_on_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('published_on_date', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('published_bool', models.BooleanField(default=False, verbose_name='Published')),
                ('author', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete='PROTECTED', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
